version: '3'

services:
  app:
    build: .
    command: python3 main.py
    # tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:0
    restart: always
    volumes:
      - .:/code
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
